import re

#ms1= '../calibrated/uid___A002_Xaca510_X78d.ms.split.cal'

#print "# Split and Shift the source to phase center"
#split2(vis=ms1, field='3',  outputvis='aori.ms', datacolumn='data')
#ms2='aori.ms'

#print "# Subtract the continuum"
#uvcontsub(vis=ms2,  
#  fitspw='0:0~190;280~959, 1:0~80;140~239, 2:0~200;450~680;1100~1919, 3:0~450;600~959, 4:0~450;1000~1200;1650~1919', 
#  combine='scan',
#  fitorder=1) 

ms4 = 'aori.ms.contsub'

#print "# Running clean on the spw 0: 28SiOv=1,J=8-7 and nu = 344.91625 GHz"
#clean(vis = ms4,
#  imagename = ms4+'.spw0_28siov1j8-7',
#  spw = '0',
#  mode = 'velocity',
#  outframe = 'lsrk',
#  veltype = 'radio',
#  restfreq='344.91625GHz',
#  interpolation = 'linear',
#  start = '-80km/s',
#  width = '0.8488km/s', 
#  nchan = 200,
#  niter = 50000, 
#  gain = 0.1,
#  threshold = '5mJy',
#  selectdata=True,
#  uvtaper=T,
#  outertaper='0.02arcsec',
#  weighting='briggs',
#  robust=0.5,
#  psfmode = 'clark',
#  imagermode = 'csclean',
#  interactive = F, 
#  mask = 'circle[[237pix,218pix],25pix]',
#  imsize = [450, 450],
#  cell = '0.005arcsec')

#print "# Running clean on the spw 1: 12COv=0,J=3-2 and nu = 345.79599 GHz"
#clean(vis = ms4,
#  imagename = ms4+'.spw1_12cov0j3-2',
#  spw = '1',
#  mode = 'velocity',
#  outframe = 'lsrk',
#  veltype = 'radio',
#  restfreq='345.79599GHz',
#  interpolation = 'linear',
#  start = '-80km/s',
#  width = '1.694km/s', # Needed here due to the error :'Requested new channel width is smaller than smallest original channel width which is 1.95311e+06 Hz or 1693.27 m/s' 
#  nchan = 100,
#  niter = 50000,
#  gain = 0.1,
#  threshold = '5mJy',
#  selectdata=True,
#  uvtaper=T,
#  outertaper='0.02arcsec',
#  weighting='briggs',
#  robust=0.5,
#  psfmode = 'clark',
#  imagermode = 'csclean',
#  interactive = F,
#  mask = 'circle[[237pix,218pix],25pix]',
#  imsize = [450, 450],
#  cell = '0.005arcsec')

#print "# Running clean on the spw 2: 29SiOv=0,J=8-7 and nu = 342.98084 GHz"
#clean(vis = ms4,
#  imagename = ms4+'.spw2_29siov0j8-7',
#  spw = '2',
#  mode = 'velocity',
#  outframe = 'lsrk',
#  veltype = 'radio',
#  restfreq='342.98084GHz',
#  interpolation = 'linear',
#  start = '-80km/s',
#  width = '0.8539km/s',
#  nchan = 200,
#  niter = 50000,
#  gain = 0.1,
#  threshold = '5mJy',
#  selectdata=True,
#  uvtaper=T,
#  outertaper='0.02arcsec',
#  weighting='briggs',
#  robust=0.5,
#  psfmode = 'clark',
#  imagermode = 'csclean',
#  interactive = F,
#  mask = 'circle[[237pix,218pix],25pix]',
#  imsize = [450, 450],
#  cell = '0.005arcsec')

#print "# Running clean on the spw 2: 28SiOv=2,J=8-7 and nu = 342.50468 GHz"
#clean(vis = ms4,
#  imagename = ms4+'.spw2_28siov2j8-7',
#  spw = '2',
#  mode = 'velocity',
#  outframe = 'lsrk',
#  veltype = 'radio',
#  restfreq='342.50438GHz',
#  interpolation = 'linear',
#  start = '-80km/s',
#  width = '0.8548km/s',
#  nchan = 200,
#  niter = 50000,
#  gain = 0.1,
#  threshold = '5mJy',
#  selectdata=True,
#  uvtaper=T,
#  outertaper='0.02arcsec',
#  weighting='briggs',
#  robust=0.5,
#  psfmode = 'clark',
#  imagermode = 'csclean',
#  interactive = F,
#  mask = 'circle[[237pix,218pix],25pix]',
#  imsize = [450, 450],
#  cell = '0.005arcsec')

#print "# Running clean on the spw 3: 13COv=0,J=3-2 and nu = 330.58797 GHz"
#clean(vis = ms4,
#  imagename = ms4+'.spw3_13cov0j3-2',
#  spw = '3',
#  mode = 'velocity',
#  outframe = 'lsrk',
#  veltype = 'radio',
#  restfreq='330.58797GHz',
#  interpolation = 'linear',
#  start = '-80km/s',
#  width = '0.886km/s',
#  nchan = 200,
#  niter = 50000,
#  gain = 0.1,
#  threshold = '5mJy',
#  selectdata=True,
#  uvtaper=T,
#  outertaper='0.02arcsec',
#  weighting='briggs',
#  robust=0.5,
#  psfmode = 'clark',
#  imagermode = 'csclean',
#  interactive = F,
#  mask = 'circle[[237pix,218pix],25pix]',
#  imsize = [450, 450],
#  cell = '0.005arcsec')

#print "# Running clean on the spw 4: 30SiOv=3,J=8-7 and nu = 331.95548 GHz"
#clean(vis = ms4,
#  imagename = ms4+'.spw4_30siov3j8-7',
#  spw = '4',
#  mode = 'velocity',
#  outframe = 'lsrk',
#  veltype = 'radio',
#  restfreq='331.95548GHz',
#  interpolation = 'linear',
#  start = '-80km/s',
#  width = '0.886km/s',
#  nchan = 200,
#  niter = 50000,
#  gain = 0.1,
#  threshold = '5mJy',
#  selectdata=True,
#  uvtaper=T,
#  outertaper='0.02arcsec',
#  weighting='briggs',
#  robust=0.5,
#  psfmode = 'clark',
#  imagermode = 'csclean',
#  interactive = F,
#  mask = 'circle[[237pix,218pix],25pix]',
#  imsize = [450, 450],
#  cell = '0.005arcsec')

print "# Running clean on the spw 4: 28SiOv=6,J=8-7 and nu = 332.87874 GHz"
clean(vis = ms4,
  imagename = ms4+'.spw4_28siov6j8-7',
  spw = '4',
  mode = 'velocity',
  outframe = 'lsrk',
  veltype = 'radio',
  restfreq='332.87874GHz',
  interpolation = 'linear',
  start = '-80km/s',
  width = '0.886km/s',
  nchan = 200,
  niter = 50000,
  gain = 0.1,
  threshold = '5mJy',
  selectdata=True,
  uvtaper=T,
  outertaper='0.02arcsec',
  weighting='briggs',
  robust=0.5,
  psfmode = 'clark',
  imagermode = 'csclean',
  interactive = F,
  mask = 'circle[[237pix,218pix],25pix]',
  imsize = [450, 450],
  cell = '0.005arcsec')

#exportfits(imagename = 'aori.ms.contsub.spw0_28siov1j8-7.image', fitsimage = 'aori.ms.contsub.spw0_28siov1j8-7.fits', history=False) 
#exportfits(imagename = 'aori.ms.contsub.spw1_12cov0j3-2.image', fitsimage = 'aori.ms.contsub.spw1_12cov0j3-2.fits', history=False)
#exportfits(imagename = 'aori.ms.contsub.spw2_28siov2j8-7.image', fitsimage = 'aori.ms.contsub.spw2_28siov2j8-7.fits', history=False)
#exportfits(imagename = 'aori.ms.contsub.spw2_29siov0j8-7.image', fitsimage = 'aori.ms.contsub.spw2_29siov0j8-7.fits', history=False)
#exportfits(imagename = 'aori.ms.contsub.spw3_13cov0j3-2.image', fitsimage = 'aori.ms.contsub.spw3_13cov0j3-2.fits', history=False)
#exportfits(imagename = 'aori.ms.contsub.spw4_30siov3j8-7.image', fitsimage = 'aori.ms.contsub.spw4_30siov3j8-7.fits', history=False)
#exportfits(imagename = 'aori.ms.contsub.spw4_28siov6j8-7.image', fitsimage = 'aori.ms.contsub.spw4_28siov6j8-7.fits', history=False)

#print "# Running clean on the entire spw 0"
#clean(vis = ms4,
#  imagename = ms4+'.spw0_all',
#  spw = '0',
#  mode = 'channel',
#  nchan = -1
#  start = 1,
#  outframe = 'lsrk',
#  veltype = 'radio',
#  interpolation = 'linear',
#  niter = 50000,
#  gain = 0.1,
#  threshold = '5mJy',
#  selectdata=True,
#  uvtaper=T,
#  outertaper='0.02arcsec',
#  weighting='briggs',
#  robust=0.5,
#  psfmode = 'clark',
#  imagermode = 'csclean',
#  interactive = F,
#  mask = 'circle[[237pix,218pix],25pix]',
#  imsize = [450, 450],
#  cell = '0.005arcsec')
#
#print "# Running clean on the entire spw 1"
#clean(vis = ms4,
#  imagename = ms4+'.spw1_all',
#  spw = '1',
#  mode = 'channel',
#  nchan = -1,
#  start = 1,
#  outframe = 'lsrk',
#  veltype = 'radio',
#  interpolation = 'linear',
#  niter = 50000,
#  gain = 0.1,
#  threshold = '5mJy',
#  selectdata=True,
#  uvtaper=T,
#  outertaper='0.02arcsec',
#  weighting='briggs',
#  robust=0.5,
#  psfmode = 'clark',
#  imagermode = 'csclean',
#  interactive = F,
#  mask = 'circle[[237pix,218pix],25pix]',
#  imsize = [450, 450],
#  cell = '0.005arcsec')
#
#print "# Running clean on the entire spw 2"
#clean(vis = ms4,
#  imagename = ms4+'.spw2_all',
#  spw = '2',
#  mode = 'channel',
#  nchan = -1,
#  start = 1,
#  outframe = 'lsrk',
#  veltype = 'radio',
#  interpolation = 'linear',
#  niter = 50000,
#  gain = 0.1,
#  threshold = '5mJy',
#  selectdata=True,
#  uvtaper=T,
#  outertaper='0.02arcsec',
#  weighting='briggs',
#  robust=0.5,
#  psfmode = 'clark',
#  imagermode = 'csclean',
#  interactive = F,
#  mask = 'circle[[237pix,218pix],25pix]',
#  imsize = [450, 450],
#  cell = '0.005arcsec')
#
#print "# Running clean on the entire spw 3"
#clean(vis = ms4,
#  imagename = ms4+'.spw3_all',
#  spw = '3',
#  mode = 'channel',
#  nchan = -1,
#  start = 1,
#  outframe = 'lsrk',
#  veltype = 'radio',
#  interpolation = 'linear',
#  niter = 50000,
#  gain = 0.1,
#  threshold = '5mJy',
#  selectdata=True,
#  uvtaper=T,
#  outertaper='0.02arcsec',
#  weighting='briggs',
#  robust=0.5,
#  psfmode = 'clark',
#  imagermode = 'csclean',
#  interactive = F,
#  mask = 'circle[[237pix,218pix],25pix]',
#  imsize = [450, 450],
#  cell = '0.005arcsec')
#
#print "# Running clean on the entire spw 4"
#clean(vis = ms4,
#  imagename = ms4+'.spw4_all',
#  spw = '4',
#  mode = 'channel',
#  nchan = -1,
#  start = 1,
#  outframe = 'lsrk',
#  veltype = 'radio',
#  interpolation = 'linear',
#  niter = 50000,
#  gain = 0.1,
#  threshold = '5mJy',
#  selectdata=True,
#  uvtaper=T,
#  outertaper='0.02arcsec',
#  weighting='briggs',
#  robust=0.5,
#  psfmode = 'clark',
#  imagermode = 'csclean',
#  interactive = F,
#  mask = 'circle[[237pix,218pix],25pix]',
#  imsize = [450, 450],
#  cell = '0.005arcsec')
